import { jsPDF } from 'jspdf';

export const exportPracticePlanToPDF = (plan, practiceDate) => {
  const doc = new jsPDF();

  // Page setup
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (2 * margin);
  let yPosition = margin;

  // Helper function to check if we need a new page
  const checkPageBreak = (neededSpace) => {
    if (yPosition + neededSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper function to wrap text
  const wrapText = (text, maxWidth) => {
    return doc.splitTextToSize(text, maxWidth);
  };

  // Title
  doc.setFontSize(20);
  doc.setFont(undefined, 'bold');
  doc.text(plan.name, margin, yPosition);
  yPosition += 10;

  // Date
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  const formattedDate = new Date(practiceDate).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Practice Date: ${formattedDate}`, margin, yPosition);
  yPosition += 6;

  // Metadata
  const totalTime = plan.drillBlocks.reduce((sum, block) => sum + block.duration, 0);
  doc.text(`Level: ${plan.level} | Duration: ${totalTime} minutes | Drills: ${plan.drillBlocks.length}`, margin, yPosition);
  yPosition += 6;

  // Focus Areas
  if (plan.focusAreas && plan.focusAreas.length > 0) {
    doc.text(`Focus: ${plan.focusAreas.join(', ')}`, margin, yPosition);
    yPosition += 10;
  } else {
    yPosition += 6;
  }

  // Separator line
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 8;

  // Drill blocks
  plan.drillBlocks.forEach((block, index) => {
    const drill = block.drill; // Drill object should be passed in

    // Check if we need space for the drill header (about 25mm)
    checkPageBreak(25);

    // Drill number and name
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    const drillTitle = `${index + 1}. ${drill?.name || 'Unknown Drill'}`;
    doc.text(drillTitle, margin, yPosition);
    yPosition += 6;

    // Duration and category
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`${block.duration} minutes | ${drill?.category || 'General'}`, margin, yPosition);
    yPosition += 6;

    // Description
    if (drill?.description) {
      doc.setTextColor(0, 0, 0);
      const descLines = wrapText(drill.description, contentWidth);
      descLines.forEach(line => {
        checkPageBreak(5);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
      yPosition += 2;
    }

    // Details (if available)
    if (drill?.details) {
      doc.setFontSize(8);
      doc.setTextColor(80, 80, 80);
      const detailLines = wrapText(drill.details, contentWidth);
      detailLines.forEach(line => {
        checkPageBreak(4);
        doc.text(line, margin, yPosition);
        yPosition += 4;
      });
      yPosition += 4;
    }

    // Separator between drills
    doc.setTextColor(0, 0, 0);
    if (index < plan.drillBlocks.length - 1) {
      checkPageBreak(6);
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.2);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 6;
    }
  });

  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by Basketball Practice Builder',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }

  // Generate filename
  const dateStr = practiceDate.replace(/-/g, '');
  const planSlug = plan.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const filename = `practice-${planSlug}-${dateStr}.pdf`;

  // Save the PDF
  doc.save(filename);
};
